# rotor.py
from collections.abc import Sequence

import torch


class Rotor:
    """
    Rotor dynamics simulator for multi-rotor systems.

    Args:
        rotor_directions (torch.Tensor): shape (num_envs, num_rotors)
            Rotation direction of each rotor (+1 for CCW, -1 for CW).
        thrust_coeff (float): Coefficient mapping thrust command to force.
        torque_coeff (float): Coefficient mapping thrust command to torque.
        rotor_ids (torch.Tensor): shape (num_rotors,) optional unique IDs.
        device (torch.device): Torch device (e.g., torch.device("cuda")).
    """

    def __init__(
        self,
        env_num: int,
        directions: torch.Tensor,
        rotor_ids: slice | torch.Tensor | list,
        thrust_coeff: float = 1.0,
        torque_coeff: float = 0.02,
        device: torch.device | str | None = None,
    ):
        self.device = device or directions.device
        self.directions = directions.to(self.device)  # (N_env, N_rotor)
        self.thrust_coeff = thrust_coeff
        self.torque_coeff = torque_coeff
        self.env_num = env_num
        self.rotor_ids = rotor_ids  # (N_rotor,)
        self.rotor_num = len(directions)

        # rotor_ids: useful for indexing/logging
        if rotor_ids is None:
            raise KeyError("rotor_ids is none, must be provided.")
            return

    def compute_dynamics(self, thrusts: torch.Tensor):
        """
        Compute the net force and torque generated by the rotors.

        Args:
            thrusts (torch.Tensor): shape (num_envs, num_rotors)
                Thrust magnitudes for each rotor.

        Returns:
            force (torch.Tensor): shape (num_envs, num_rotors, 3)
                Local-frame force vector.
            torque (torch.Tensor): shape (num_envs, num_rotors, 3)
                Local-frame torque vector.
        """
        # Ensure correct shape
        assert thrusts.shape == (
            self.env_num,
            self.rotor_num,
        ), f"Expected thrusts shape {(self.env_num, self.rotor_num)}, got {thrusts.shape}"

        # TODO: thrust system model, maybe second order dynamics

        # TODO: rotor gyroscopic moments

        # Compute individual rotor forces (rotor z-axis aligned thrust)
        # Force direction assumed along +z axis of the rotor frame
        forces = torch.zeros((self.env_num, self.rotor_num, 3), device=self.device)
        forces[:, :, 2] = self.thrust_coeff * thrusts  # (N_env, N_rotor, 3)

        # Compute torques from spinning direction
        # τ = r × F + τ_spin
        torque = torch.zeros((self.env_num, self.rotor_num, 3), device=self.device)
        torque[:, :, 2] = self.torque_coeff * thrusts * self.directions  # (N_env, N_rotor, 3)

        return forces, torque


# debug.py


def main():
    """Main function."""
    rotors = Rotor(
        env_num=32,
        directions=torch.tensor([1, -1, 1, -1], dtype=torch.float32),
        thrust_coeff=1.0,
        torque_coeff=0.02,
        rotor_ids=torch.tensor([0, 1, 2, 3], dtype=torch.int32),
        device=torch.device("cpu"),
    )
    import ipdb

    ipdb.set_trace()
    print("Rotor initialized.")
    print(f"Directions: {rotors.directions}")
    thrusts = torch.rand((32, 4), dtype=torch.float32)
    forces, torques = rotors.compute_dynamics(thrusts)
    print(f"Forces: {forces}")
    print(f"Torques: {torques}")


if __name__ == "__main__":
    # run the main function
    main()
    # close sim app
